name: Generate ASCII Artwork
on: push
jobs:
  build_job_1:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
  
      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON......RAWRRRR" >> dragon.txt
      
      - name: Sleep for 30 seconds
        run:  sleep 30

  test_job_2:
    runs-on: ubuntu-22.04
    steps:
      - name: Sleeps for 10 seconds
        run: sleep 10
      
      - name: Test File exits
        run: cat dragon.txt | grep -i "DRAGON"
  deploy_job_3:
    runs-on: ubuntu-22.04
    steps:
      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying ASCII Artwork"