name: Exploring Variables and Secrets
############ Environmental variables at WORKFLOW level ############
on: push
env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME:  bruno101
  IMAGE_NAME: github-actions-nginx
jobs:
  docker:
    runs-on: ubuntu-22.04
############ Environmental variables at STEP level ############

    steps:
      - name: Docker Build
        # env:
        #   CONTAINER_REGISTRY: docker.io
        #   DOCKER_USERNAME:  bruno101
        #   IMAGE_NAME: github-actions-nginx
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest 

      - name: Docker login
        env:
          DOCKER_PASSWORD: "@Lee2016?!"
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
      
      - name: Docker Pusblish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-22.04
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8088:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest


